version: "3"

services:
  app:
    container_name: spa-front
    build: . # Путь к Dockerfile вашего приложения
    ports:
      - "3000:3000" # Предполагается, что ваше приложение слушает на порту 3000
